config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'songs/hourock' => 'songs#hourock'
  get 'songs/kpop' => 'songs#kpop'
  get 'songs/yougakupop' => 'songs#yougakupop'
  get 'songs/yougakurock' => 'songs#yougakurock'
  get 'songs/anison' => 'songs#anison'
  get 'songs/classic' => 'songs#classic'
  get 'songs/hiphop' => 'songs#hiphop'
  get 'songs/randb' => 'songs#randb'
  get 'songs/jpop' => 'songs#jpop'
  get 'songs/vocaloid' => 'songs#vocaloid'
  get 'songs/search' => 'songs#search'

  resources :users, only: [:show]
  resources :perfumes

  resources :songs do
    resources :likes, only: [:create, :destroy]
  end
  root 'songs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :song
  belongs_to :user
  validates_uniqueness_of :song_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :songs, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_songs, through: :likes, source: :song

  def already_liked?(song)
    self.likes.exists?(song_id: song.id)
  end

  validates :name, presence: true
  validates :profile, length: { maximum: 200}
  mount_uploader :image, ImageUploader



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(song_id: params[:song_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(song_id: params[:song_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
    
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController
    def index
    end

    def new
        @song = Perfume.new
    end

    def show
        @song = Perfume.find_by(id: params[:id])
    end

    def create
        perfume = Perfume.new(perfume_params)
        if perfume.save
            flash[:notice] = "診断が完了しました"
            redirect_to perfume_path(perfume.id)
        else
            redirect_to :action => "new"
        end
    end

    private
    def perfume_params
        params.require(:perfume).permit(:question1, :question2, :question3, :question4)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    before_action :authenticate_user!, only: [:new, :create]

    def index
      if params[:search] != nil && params[:search] != ''
        #部分検索かつ複数検索
        search = params[:search]
        @songs = Song.where("name LIKE ? OR singer LIKE ? OR genre LIKE ? OR about LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
      else
        @songs = Song.all
      end
    end

    def new
        @song = Song.new
    end
    
    def create
      song = Song.new(song_params)
      song.user_id = current_user.id
    
      if song.save
        case song.category
        when "jpop"
          redirect_to action: "jpop"
        when "hourock"
          redirect_to action: "hourock"
        when "kpop"
          redirect_to action: "kpop"
        when "anison"
          redirect_to action: "anison"
        when "vocaloid"
          redirect_to action: "vocaloid"
        when "hiphop"
          redirect_to action: "hiphop"
        when "randb"
          redirect_to action: "randb"
        when "yougakupop"
          redirect_to action: "yougakupop"
        when "yougakurock"
          redirect_to action: "yougakurock"
        when "classic"
          redirect_to action: "classic"
        else
          redirect_to action: "index"
        end
      else
        redirect_to action: "new"
      end
    end
    

    def hourock
      @hourocks = Song.where(category:"hourock")
    end
  
    def kpop
      @kpops = Song.where(category:"kpop")
    end
  
    def yougakupop
      @yougakupops = Song.where(category:"yougakupop")
    end

    def yougakurock
      @yougakurocks = Song.where(category:"yougakurock")
    end

    def jpop
      @jpops = Song.where(category:"jpop")
    end
  
    def vocaloid
      @vocaloids = Song.where(category:"vocaloid")
    end
  
    def anison
      @anisons = Song.where(category:"anison")
    end

    def classic
      @classics = Song.where(category:"classic")
    end
  
    def hiphop
      @hiphops = Song.where(category:"hiphop")
    end
  
    def randb
      @randbs = Song.where(category:"randb")
    end


    def show
      @song = Song.find(params[:id])
    end

    def edit
      @song = Song.find(params[:id])
    end

    def update
      song = Song.find(params[:id])
      if song.update(song_params)
        redirect_to :action => "show", :id => song.id
      else
        redirect_to :action => "new"
      end
    end

    def destroy
      song = Song.find(params[:id])
      song.destroy
      redirect_to action: :index
    end
    
    private
    def song_params
      params.require(:song).permit(:name, :genre, :singer, :about, :movie, :user_id, :image, :category, :youtube_url)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
    def find_youtube_url(youtube_url)
        if youtube_url[0..16] == "https://youtu.be/"
            return youtube_url[17..27]
        else
            return youtube_url[32..42]
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/778dfc0ca0.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Mochiy+Pop+P+One&family=Reenie+Beanie&display=swap"
    rel="stylesheet"/>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
  <h1><%= link_to "Musicvoyage", songs_path %></h1>
  <div class="header-list">
    <ul>
      <% if user_signed_in? %>
      <li><%= link_to "Search", songs_search_path %></li>
      <li><%= link_to "Post", new_song_path %></li>
      <li><%= link_to "Try", perfumes_path %></li>
      <li><%= link_to "Mypage", user_path(current_user.id) %></li>
      <li><%= button_to 'Logout', destroy_user_session_path, method: :delete, class: 'logout' %></li>

    
      <% else %>
      <li><%= link_to "Search", songs_search_path %></li>
      <li><%= link_to "Post", new_song_path %></li>
      <li><%= link_to "Try", perfumes_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
  </header>

  <body>
    <%= yield %>
  </body>

  <footer>
    <small>©Kimi Sekine 2024</small>
  </footer>
</html>

app/views/songs/anison.html.erb
<%= stylesheet_link_tag 'genre', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>アニソン</h1>
        <div class="container">
                < div class="item">
                    <% @anisons.each do |t| %>
                    <% if t.category == "anison" %> 
                        <p><%= image_tag t.image_url, size: "250x250" if t.image? %></p>
                        <p><%= t.name %></p>
                        
                        <p><%= t.singer %></p>
                    <% end %>
                    <%= link_to "詳細へ", song_path(t.id) %>
                    <% end %>
                </div>
                <%= link_to "みんなの投稿一覧に戻る", songs_path %>
        </div>
</div>

app/views/songs/classic.html.erb
<%= stylesheet_link_tag 'genre', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>クラシック</h1>
        <div class="container">
                <div class="content">
                <% @classics.each do |t| %>
                    <% if t.category == "classic" %> 
                    <p><%= image_tag t.image_url, size: "250x250" if t.image? %></p>
                        <p><%= t.name %></p>
                        <p><%= t.singer %></p>
                    <% end %>
                    <%= link_to "詳細へ", song_path(t.id) %>
                <% end %>
                
                <%= link_to "みんなの投稿一覧に戻る", songs_path %>
                </div>
        </div>
</div>

app/views/songs/hiphop.html.erb
<%= stylesheet_link_tag 'genre', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>HIPHOP</h1>
        <div class="container">
                <div class="content">
                <% @hiphops.each do |t| %>
                    <% if t.category == "hiphop" %> 
                    <p><%= image_tag t.image_url, size: "250x250" if t.image? %></p>
                        <p><%= t.name %></p>
                        <p><%= t.singer %></p>
                    <% end %>
                    <%= link_to "詳細へ", song_path(t.id) %>
                <% end %>
                
                <%= link_to "みんなの投稿一覧に戻る", songs_path %>
                </div>
        </div>
</div>

app/views/songs/hourock.html.erb
<%= stylesheet_link_tag 'genre', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>邦ロック</h1>
        <div class="container">
                <div class="content">
                <% @hourocks.each do |t| %>
                    <% if t.category == "hourock" %> 
                    <p><%= image_tag t.image_url, size: "250x250" if t.image? %></p>
                        <p><%= t.name %></p>
                        <p><%= t.singer %></p>
                    <% end %>
                    <%= link_to "詳細へ", song_path(t.id) %>
                <% end %>
                
                <%= link_to "みんなの投稿一覧に戻る", songs_path %>
                </div>
        </div>
</div>

app/views/songs/index.html.erb
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="slider r_to_l">
    <div class="slider_inner">
        <div><%= image_tag 'slide1.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide2.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide3.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide4.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide5.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
    </div>
    <div class="slider_inner">
        <div><%= image_tag 'slide1.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide2.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide3.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide4.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide5.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
    </div>
</div>

<div class="slider l_to_r">
    <div class="slider_inner">
        <div><%= image_tag 'slide6.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide7.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide8.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide11.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide10.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
    </div>
    <div class="slider_inner">
        <div><%= image_tag 'slide6.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide7.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide8.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide11.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide10.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
    </div>
</div>

<h1 class="title">MusicVoyage</h1>

<div class="slider r_to_l">
    <div class="slider_inner">
        <div><%= image_tag 'slide1.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide2.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide3.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide4.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide5.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
    </div>
    <div class="slider_inner">
        <div><%= image_tag 'slide1.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide2.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide3.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide4.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide5.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
    </div>
</div>


<div class="slider l_to_r">
    <div class="slider_inner">
        <div><%= image_tag 'slide6.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide7.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide8.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide11.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide10.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
    </div>
    <div class="slider_inner">
        <div><%= image_tag 'slide6.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide7.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide8.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide11.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
        <div><%= image_tag 'slide10.jpg', :class=>"photo", :alt => '画像', :size => "400px" %></div>
    </div>
</div>



Resources

<div class="main-container">
        <div class="container">
            <h2>-----------　　　ジャンル別で探す　　　-----------</h2>
                <div class="content">
                <p>
                    <%= link_to songs_jpop_path do %>
                        <div class="record-container">
                            <span class="record-text">J-POP</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
                <p>
                    <%= link_to songs_hourock_path do %>
                        <div class="record-container">
                            <span class="record-text">邦楽ロック</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
                <p>
                    <%= link_to songs_kpop_path do %>
                        <div class="record-container">
                            <span class="record-text">K-POP</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
                <p>
                    <%= link_to songs_anison_path do %>
                        <div class="record-container">
                            <span class="record-text">アニソン</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
                <p>
                    <%= link_to songs_vocaloid_path do %>
                        <div class="record-container">
                            <span class="record-text">VOCALOID</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
            </div>


            <div class="content">
                <p>
                    <%= link_to songs_hiphop_path do %>
                        <div class="record-container">
                            <span class="record-text">HIPHOP&RAP</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
                <p>
                    <%= link_to songs_randb_path do %>
                        <div class="record-container">
                            <span class="record-text">R&B</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
                <p>
                    <%= link_to songs_yougakupop_path do %>
                        <div class="record-container">
                            <span class="record-text">洋楽ポップ</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
                <p>
                    <%= link_to songs_yougakurock_path do %>
                        <div class="record-container">
                            <span class="record-text">洋楽ロック</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
                <p>
                    <%= link_to songs_classic_path do %>
                        <div class="record-container">
                            <span class="record-text">クラシック</span>
                            <%= image_tag "redrecord2.jpg", class: "record" %>
                        </div>
                    <% end %>
                </p>
            </div>
                
        </div>

        <div class="container">
            <h2>-----------　　　Post　　　-----------</h2>
                <div class="content">
                    <%= link_to "新規投稿する", new_song_path %>
                </div>
        </div>

        <div class="container">
            <h2>-----------　　　Try　　　-----------</h2>
                <div class="content">
                    <%= link_to "診断する", perfumes_path %>
                </div>
        </div>
</div>

app/views/songs/jpop.html.erb
<%= stylesheet_link_tag 'genre', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>J-POP</h1>
    <div class="container">
        <% @jpops.each do |t| %>
            <div class="satoko">
                <% if t.category == "jpop" %> 
                <p><%= image_tag t.image_url, size: "250x250" if t.image? %></p>
                    <p><%= t.name %></p>
                    <p><%= t.singer %></p>
                <% end %>
                <%= link_to "詳細へ", song_path(t.id) %>
            </div>
        <% end %>
        <%= link_to "ジャンル選択に戻る", songs_search_path %>
        </div>
    </div>
</div>

app/views/songs/randb.html.erb
<%= stylesheet_link_tag 'genre', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>R&B</h1>
        <div class="container">
                <div class="content">
                <% @randbs.each do |t| %>
                    <% if t.category == "randb" %> 
                    <p><%= image_tag t.image_url, size: "250x250" if t.image? %></p>
                        <p><%= t.name %></p>
                        <p><%= t.singer %></p>
                    <% end %>
                    <%= link_to "詳細へ", song_path(t.id) %>
                <% end %>
                
                <%= link_to "みんなの投稿一覧に戻る", songs_path %>
                </div>
        </div>
</div>

app/views/songs/search.html.erb
<%= stylesheet_link_tag 'search', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>ジャンルを選ぶ</h1>
    <div class="container">
        <div class="content">
                <%= link_to "J-POP",  songs_jpop_path %>
            </div>

        <div class="content">
                <%= link_to "邦楽ロック",  songs_hourock_path %>
            </div>

        <div class="content">
                <%= link_to "K-POP",  songs_kpop_path %>
            </div>
        

        <div class="content">
                <%= link_to "アニソン",  songs_anison_path %>
            </div>
        

        <div class="content">
                <%= link_to "ボーカロイド",  songs_vocaloid_path %>
            </div>
        

        <div class="content">
            <%= link_to "ヒップホップ・ラップ",  songs_hiphop_path %>
            </div>
        

        <div class="content">
                <%= link_to "R&B",  songs_randb_path %>
            </div>
        

        <div class="content">
                <%= link_to "洋楽ポップ", songs_yougakupop_path %>
            </div>
        

        <div class="content">
                <%= link_to "洋楽ロック",  songs_yougakurock_path %>
            </div>
        

        <div class="content">
                <%= link_to "クラシック",  songs_classic_path %>
            </div>
    </div>
</div>

<footer>
    <small>©Kimi Sekine</small>
</footer>

app/views/songs/show.html.erb
<%= stylesheet_link_tag 'show', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>投稿詳細</h1>
        <div class="song">
        <p><%= image_tag @song.image_url, size: "250x200" if @song.image? %></p>
            <p><%= @song.name %></p>
            <p><%= @song.genre %></p>
            <p><%= @song.singer %></p>
            <p><%= @song.about %></p>
                <% if user_signed_in? %>
                <% if current_user.already_liked?(@song) %>
                <%= link_to song_like_path(@song), method: :delete do %>
                    <i class="fa-solid fa-heart"></i><%= @song.likes.count %>
                <% end %>
                <% else %>
                <%= link_to song_likes_path(@song), method: :post do %>
                    <i class="fa-regular fa-heart"></i><%= @song.likes.count %>
                <% end %>
                <% end %>
                <% else %>
                <i class="fa-regular fa-heart"><%= @song.likes.count %>
                <% end %>
                <% if user_signed_in? && current_user.id == @song.user_id %>
            <%= link_to "編集する", edit_song_path(@song.id) %>
            <%= link_to "削除する", songs_path(@song.id), date:{turbo_method: :delete} %>
          <% end %> 
    
        </div>
                <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(@song.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <h2>いいねしたユーザー</h2>
                    <% @song.liked_users.each do |user| %>
                    <li><%= user.email %></li>
                    <% end %>

                <%= link_to "みんなの投稿一覧に戻る", songs_path %>
        </div>

        <a href="#" onclick="history.back()">前のページへ戻る</a>

app/views/songs/vocaloid.html.erb
<%= stylesheet_link_tag 'genre', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>ボーカロイド</h1>
        <div class="container">
                <div class="content">
                <% @vocaloids.each do |t| %>
                    <% if t.category == "vocaloid" %> 
                    <p><%= image_tag t.image_url, size: "250x250" if t.image? %></p>
                        <p><%= t.name %></p>
                        <p><%= t.singer %></p>
                    <% end %>
                    <%= link_to "詳細へ", song_path(t.id) %>
                <% end %>
                
                <%= link_to "みんなの投稿一覧に戻る", songs_path %>
                </div>
        </div>
</div>

app/views/songs/yougakupop.html.erb
<%= stylesheet_link_tag 'genre', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="main-container">
    <h1>洋楽ポップス</h1>
        <div class="container">
                <div class="content">
                <% @yougakupops.each do |t| %>
                    <% if t.category == "yougaku" %> 
                    <p><%= image_tag t.image_url, size: "250x250" if t.image? %></p>
                        <p><%= t.name %></p>
                        <p><%= t.singer %></p>
                    <% end %>
                    <%= link_to "詳細へ", song_path(t.id) %>
                <% end %>
                
                <%= link_to "みんなの投稿一覧に戻る", songs_path %>
                </div>
        </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>